[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "budget habit bounce fun magnet update shallow position prevent air subject have dismiss cradle hold lobster forget swap meadow pledge price bike pencil lemon"
